### ISSUE TITLE
datafile.py error

### ISSUE THREAD

**Issue by chilledgaz** [etingof/snmpsim#123]
Hello,

Happy New Year!

I wonder if someone could possibly help with this error please?

C:\Program Files\SNMP Simulator\Data>datafile.py --ignore-broken-records --source-record-type=sapwalk --destination-record-type=snmprec --input-file=hp.sapwalk --output-file=hp.snmprec
# Input file #0, processing records from the beginning till the end
Traceback (most recent call last):
  File "C:\Users\chilled\AppData\Local\Programs\Python\Python38\Scripts\datafile.py", line 202, in <module>
    oid, value = recordsSet[srcRecordType].evaluate(line, backdoor=backdoor)
  File "c:\users\chilled\appdata\local\programs\python\python38\lib\site-packages\snmpsim\record\dump.py", line 41, in evaluate
    oid, tag, value = self.grammar.parse(line)
  File "c:\users\chilled\appdata\local\programs\python\python38\lib\site-packages\snmpsim\grammar\sap.py", line 43, in parse
    return oid, tag, self.filterMap.get(tag, lambda x: x)(value.strip())
  File "c:\users\chilled\appdata\local\programs\python\python38\lib\site-packages\snmpsim\grammar\sap.py", line 29, in __stringFilter
    value = [int(value[x:x + 2], 16) for x in range(2, len(value[2:]) + 2, 2)]
  File "c:\users\chilled\appdata\local\programs\python\python38\lib\site-packages\snmpsim\grammar\sap.py", line 29, in <listcomp>
    value = [int(value[x:x + 2], 16) for x in range(2, len(value[2:]) + 2, 2)]
ValueError: invalid literal for int() with base 16: ',0'

C:\Program Files\SNMP Simulator\Data>

The command fails for HP devices but works for non-HP devices.

Best wishes,

chilledgaz

**Comment by gainskills** [comment]
Hi, could you share the file: hp.sapwalk ?
