### ISSUE TITLE
arg parser missing `row_hint` or `row-hint`

### ISSUE THREAD

**Issue by mmodenesi** [etingof/snmpsim#133]
```
/app # snmpsim-record-mibs --mib-module=IF-MIB
# MIB module: IF-MIB, from the beginning till the end
Traceback (most recent call last):
  File "/usr/local/bin/snmpsim-record-mibs", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/snmpsim/commands/mib2rec.py", line 461, in main
    if not args.row_hint:
AttributeError: 'Namespace' object has no attribute 'row_hint'
```

**Comment by gainskills** [comment]
can you try the fork: https://github.com/gainskills/snmpsim to see if it works as expected?

**Comment by mmodenesi** [comment]
@gainskills it works
