### ISSUE TITLE
rec2rec - AttributeError: 'Namespace' object has no attribute 'mib_source'

### ISSUE THREAD

**Issue by dschultzca** [etingof/snmpsim#140]
Running the command to convert snmpwalk to snmprec, I encounter this error.
I installed master from this repo 2 weeks ago.  Using Python 3.6.8 on CentOS Linux release 7.7.1908 (Core)
```
[user@server data]$ snmpsim-manage-records --input-file=modem.snmpwalk --source-record-type=snmpwalk
Traceback (most recent call last):
  File "/home/dale/py3venv/snmp_sim/bin/snmpsim-manage-records", line 11, in <module>
    load_entry_point('snmpsim==1.0.0', 'console_scripts', 'snmpsim-manage-records')()
  File "/home/dale/py3venv/snmp_sim/lib64/python3.6/site-packages/snmpsim/commands/rec2rec.py", line 154, in main
    if not args.mib_source:
AttributeError: 'Namespace' object has no attribute 'mib_source'
```

**Comment by thekafkaf** [comment]
Its a typo and there are some more similar naming errors I fixed in #142

**Comment by gainskills** [comment]
> Its a typo and there are some more similar naming errors I fixed in #142

Could you please suggest how you resolved the "AttributeError: 'Namespace' object has no attribute '_xxx_'" issue?

There is a similar issue https://github.com/etingof/snmpsim/issues/147, want to see if I could fix it by follow your way.

Thanks,
