### ISSUE TITLE
Fresh install snmpsim-command-responder --data-dir=./data --agent-udpv4-endpoint=127.0.0.1:1024 not working

### ISSUE THREAD

**Issue by tkekan** [etingof/snmpsim#150]
Setup log:
17:01 $ python setup.py install
running install
running bdist_egg
running egg_info
creating snmpsim.egg-info
writing requirements to snmpsim.egg-info/requires.txt
writing snmpsim.egg-info/PKG-INFO
writing top-level names to snmpsim.egg-info/top_level.txt
writing dependency_links to snmpsim.egg-info/dependency_links.txt
writing entry points to snmpsim.egg-info/entry_points.txt
writing manifest file 'snmpsim.egg-info/SOURCES.txt'
reading manifest file 'snmpsim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'snmpsim.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.14-intel/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/snmpsim
copying snmpsim/controller.py -> build/lib/snmpsim
copying snmpsim/datafile.py -> build/lib/snmpsim
copying snmpsim/error.py -> build/lib/snmpsim
copying snmpsim/log.py -> build/lib/snmpsim
copying snmpsim/__init__.py -> build/lib/snmpsim
copying snmpsim/utils.py -> build/lib/snmpsim
copying snmpsim/variation.py -> build/lib/snmpsim
copying snmpsim/confdir.py -> build/lib/snmpsim
copying snmpsim/endpoints.py -> build/lib/snmpsim
copying snmpsim/daemon.py -> build/lib/snmpsim
creating build/lib/snmpsim/reporting
copying snmpsim/reporting/__init__.py -> build/lib/snmpsim/reporting
copying snmpsim/reporting/manager.py -> build/lib/snmpsim/reporting
creating build/lib/snmpsim/grammar
copying snmpsim/grammar/abstract.py -> build/lib/snmpsim/grammar
copying snmpsim/grammar/__init__.py -> build/lib/snmpsim/grammar
copying snmpsim/grammar/dump.py -> build/lib/snmpsim/grammar
copying snmpsim/grammar/walk.py -> build/lib/snmpsim/grammar
copying snmpsim/grammar/snmprec.py -> build/lib/snmpsim/grammar
copying snmpsim/grammar/sap.py -> build/lib/snmpsim/grammar
copying snmpsim/grammar/mvc.py -> build/lib/snmpsim/grammar
creating build/lib/snmpsim/record
copying snmpsim/record/abstract.py -> build/lib/snmpsim/record
copying snmpsim/record/__init__.py -> build/lib/snmpsim/record
copying snmpsim/record/dump.py -> build/lib/snmpsim/record
copying snmpsim/record/walk.py -> build/lib/snmpsim/record
copying snmpsim/record/snmprec.py -> build/lib/snmpsim/record
copying snmpsim/record/sap.py -> build/lib/snmpsim/record
copying snmpsim/record/mvc.py -> build/lib/snmpsim/record
creating build/lib/snmpsim/commands
copying snmpsim/commands/__init__.py -> build/lib/snmpsim/commands
copying snmpsim/commands/pcap2rec.py -> build/lib/snmpsim/commands
copying snmpsim/commands/mib2rec.py -> build/lib/snmpsim/commands
copying snmpsim/commands/responder_lite.py -> build/lib/snmpsim/commands
copying snmpsim/commands/cmd2rec.py -> build/lib/snmpsim/commands
copying snmpsim/commands/rec2rec.py -> build/lib/snmpsim/commands
copying snmpsim/commands/responder.py -> build/lib/snmpsim/commands
creating build/lib/snmpsim/reporting/formats
copying snmpsim/reporting/formats/alljson.py -> build/lib/snmpsim/reporting/formats
copying snmpsim/reporting/formats/null.py -> build/lib/snmpsim/reporting/formats
copying snmpsim/reporting/formats/__init__.py -> build/lib/snmpsim/reporting/formats
copying snmpsim/reporting/formats/base.py -> build/lib/snmpsim/reporting/formats
creating build/lib/snmpsim/record/search
copying snmpsim/record/search/database.py -> build/lib/snmpsim/record/search
copying snmpsim/record/search/__init__.py -> build/lib/snmpsim/record/search
copying snmpsim/record/search/file.py -> build/lib/snmpsim/record/search
creating build/bdist.macosx-10.14-intel
creating build/bdist.macosx-10.14-intel/egg
creating build/bdist.macosx-10.14-intel/egg/snmpsim
creating build/bdist.macosx-10.14-intel/egg/snmpsim/reporting
creating build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats
copying build/lib/snmpsim/reporting/formats/alljson.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats
copying build/lib/snmpsim/reporting/formats/null.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats
copying build/lib/snmpsim/reporting/formats/__init__.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats
copying build/lib/snmpsim/reporting/formats/base.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats
copying build/lib/snmpsim/reporting/__init__.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/reporting
copying build/lib/snmpsim/reporting/manager.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/reporting
creating build/bdist.macosx-10.14-intel/egg/snmpsim/grammar
copying build/lib/snmpsim/grammar/abstract.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/grammar
copying build/lib/snmpsim/grammar/__init__.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/grammar
copying build/lib/snmpsim/grammar/dump.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/grammar
copying build/lib/snmpsim/grammar/walk.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/grammar
copying build/lib/snmpsim/grammar/snmprec.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/grammar
copying build/lib/snmpsim/grammar/sap.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/grammar
copying build/lib/snmpsim/grammar/mvc.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/grammar
copying build/lib/snmpsim/controller.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
copying build/lib/snmpsim/datafile.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
creating build/bdist.macosx-10.14-intel/egg/snmpsim/record
copying build/lib/snmpsim/record/abstract.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record
copying build/lib/snmpsim/record/__init__.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record
creating build/bdist.macosx-10.14-intel/egg/snmpsim/record/search
copying build/lib/snmpsim/record/search/database.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record/search
copying build/lib/snmpsim/record/search/__init__.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record/search
copying build/lib/snmpsim/record/search/file.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record/search
copying build/lib/snmpsim/record/dump.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record
copying build/lib/snmpsim/record/walk.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record
copying build/lib/snmpsim/record/snmprec.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record
copying build/lib/snmpsim/record/sap.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record
copying build/lib/snmpsim/record/mvc.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/record
copying build/lib/snmpsim/error.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
copying build/lib/snmpsim/log.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
copying build/lib/snmpsim/__init__.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
copying build/lib/snmpsim/utils.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
copying build/lib/snmpsim/variation.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
creating build/bdist.macosx-10.14-intel/egg/snmpsim/commands
copying build/lib/snmpsim/commands/__init__.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/commands
copying build/lib/snmpsim/commands/pcap2rec.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/commands
copying build/lib/snmpsim/commands/mib2rec.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/commands
copying build/lib/snmpsim/commands/responder_lite.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/commands
copying build/lib/snmpsim/commands/cmd2rec.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/commands
copying build/lib/snmpsim/commands/rec2rec.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/commands
copying build/lib/snmpsim/commands/responder.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/commands
copying build/lib/snmpsim/confdir.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
copying build/lib/snmpsim/endpoints.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
copying build/lib/snmpsim/daemon.py -> build/bdist.macosx-10.14-intel/egg/snmpsim
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats/alljson.py to alljson.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats/null.py to null.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/formats/base.py to base.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/reporting/manager.py to manager.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/grammar/abstract.py to abstract.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/grammar/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/grammar/dump.py to dump.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/grammar/walk.py to walk.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/grammar/snmprec.py to snmprec.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/grammar/sap.py to sap.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/grammar/mvc.py to mvc.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/controller.py to controller.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/datafile.py to datafile.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/abstract.py to abstract.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/search/database.py to database.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/search/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/search/file.py to file.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/dump.py to dump.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/walk.py to walk.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/snmprec.py to snmprec.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/sap.py to sap.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/record/mvc.py to mvc.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/error.py to error.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/log.py to log.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/utils.py to utils.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/variation.py to variation.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/commands/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/commands/pcap2rec.py to pcap2rec.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/commands/mib2rec.py to mib2rec.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/commands/responder_lite.py to responder_lite.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/commands/cmd2rec.py to cmd2rec.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/commands/rec2rec.py to rec2rec.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/commands/responder.py to responder.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/confdir.py to confdir.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/endpoints.py to endpoints.pyc
byte-compiling build/bdist.macosx-10.14-intel/egg/snmpsim/daemon.py to daemon.pyc
installing package data to build/bdist.macosx-10.14-intel/egg
running install_data
creating build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/error.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/notification.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/subprocess.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/redis.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/delay.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/multiplex.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/numeric.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/sql.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
copying variation/writecache.py -> build/bdist.macosx-10.14-intel/egg/snmpsim/variation
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data
copying data/public.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/1.3.6.1.6.1.1.0
copying data/1.3.6.1.6.1.1.0/127.0.0.1.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/1.3.6.1.6.1.1.0
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/mib2dev
copying data/mib2dev/tcp-mib.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/mib2dev
copying data/mib2dev/ip-mib.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/mib2dev
copying data/mib2dev/udp-mib.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/mib2dev
copying data/mib2dev/host-resources-mib.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/mib2dev
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
copying data/variation/notification.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
copying data/variation/error.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
copying data/variation/subprocess.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
copying data/variation/multiplex.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
copying data/variation/virtualtable.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
copying data/variation/sql.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
copying data/variation/writecache.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
copying data/variation/delay.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00002.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00003.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00008.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00001.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00000.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00010.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00009.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00005.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00004.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00006.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
copying data/variation/multiplex/00007.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/variation/multiplex
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/recorded
copying data/recorded/linksys-system.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/recorded
copying data/recorded/linux-full-walk.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/recorded
copying data/recorded/solaris-system.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/recorded
copying data/recorded/udp-endpoint-table-walk.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/recorded
copying data/recorded/eaton-9PX-partial-walk.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/recorded
copying data/recorded/winxp-full-walk.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/recorded
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/foreignformats
copying data/foreignformats/winxp1.snmpwalk -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/foreignformats
copying data/foreignformats/linux.snmpwalk -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/foreignformats
copying data/foreignformats/winxp2.sapwalk -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/foreignformats
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/public
copying data/public/1.3.6.1.2.1.100.1.13.0.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/public
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/public/1.3.6.1.6.1.1.0
copying data/public/1.3.6.1.6.1.1.0/127.0.0.1.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/public/1.3.6.1.6.1.1.0
creating build/bdist.macosx-10.14-intel/egg/snmpsim/data/public/1.3.6.1.2.1.100.1.2.0
copying data/public/1.3.6.1.2.1.100.1.2.0/__1.snmprec -> build/bdist.macosx-10.14-intel/egg/snmpsim/data/public/1.3.6.1.2.1.100.1.2.0
creating build/bdist.macosx-10.14-intel/egg/EGG-INFO
copying snmpsim.egg-info/PKG-INFO -> build/bdist.macosx-10.14-intel/egg/EGG-INFO
copying snmpsim.egg-info/SOURCES.txt -> build/bdist.macosx-10.14-intel/egg/EGG-INFO
copying snmpsim.egg-info/dependency_links.txt -> build/bdist.macosx-10.14-intel/egg/EGG-INFO
copying snmpsim.egg-info/entry_points.txt -> build/bdist.macosx-10.14-intel/egg/EGG-INFO
copying snmpsim.egg-info/not-zip-safe -> build/bdist.macosx-10.14-intel/egg/EGG-INFO
copying snmpsim.egg-info/requires.txt -> build/bdist.macosx-10.14-intel/egg/EGG-INFO
copying snmpsim.egg-info/top_level.txt -> build/bdist.macosx-10.14-intel/egg/EGG-INFO
creating dist
creating 'dist/snmpsim-1.0.0-py2.7.egg' and adding 'build/bdist.macosx-10.14-intel/egg' to it
removing 'build/bdist.macosx-10.14-intel/egg' (and everything under it)
Processing snmpsim-1.0.0-py2.7.egg
creating /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages/snmpsim-1.0.0-py2.7.egg
Extracting snmpsim-1.0.0-py2.7.egg to /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages
Adding snmpsim 1.0.0 to easy-install.pth file
Installing snmpsim-command-responder-lite script to /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/bin
Installing snmpsim-command-responder script to /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/bin
Installing snmpsim-record-mibs script to /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/bin
Installing snmpsim-manage-records script to /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/bin
Installing snmpsim-record-traffic script to /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/bin
Installing snmpsim-record-commands script to /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/bin

Installed /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages/snmpsim-1.0.0-py2.7.egg
Processing dependencies for snmpsim==1.0.0
Searching for pysnmp==4.4.12
Best match: pysnmp 4.4.12
Adding pysnmp 4.4.12 to easy-install.pth file

Using /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages
Searching for pyasn1==0.4.8
Best match: pyasn1 0.4.8
Adding pyasn1 0.4.8 to easy-install.pth file

Using /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages
Searching for pysmi==0.3.4
Best match: pysmi 0.3.4
Adding pysmi 0.3.4 to easy-install.pth file

Using /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages
Searching for pycryptodomex==3.9.8
Best match: pycryptodomex 3.9.8
Adding pycryptodomex 3.9.8 to easy-install.pth file

Using /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages
Searching for ply==3.11
Best match: ply 3.11
Adding ply 3.11 to easy-install.pth file

Using /Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages
Finished processing dependencies for snmpsim==1.0.0

17:02 $ snmpsim-command-responder --data-dir=./data --agent-udpv4-endpoint=127.0.0.1:1024
Using "NullReporter" activity reporting method with params  
Cache directory "/var/folders/3c/9r_ddzn520s_zg1_55nhlcvh0000gn/T/snmpsim" created 
Scanning "/Users/tkekan/.snmpsim/variation" directory for variation modules... 
Directory "/Users/tkekan/.snmpsim/variation" does not exist 
Scanning "/usr/local/share/snmpsim/variation" directory for variation modules... 
Directory "/usr/local/share/snmpsim/variation" does not exist 
Scanning "/Users/tkekan/oracle/wrk/snmp-poller/poller-venv/snmpsim/variation" directory for variation modules... 
ERROR Variation module "/Users/tkekan/oracle/wrk/snmp-poller/poller-venv/snmpsim/variation/error.py" execution failure: No module named mltsplit 
Initializing variation modules... 
Traceback (most recent call last):
  File "/Users/tkekan/oracle/wrk/snmp-poller/poller-venv/bin/snmpsim-command-responder", line 11, in <module>
    load_entry_point('snmpsim==1.0.0', 'console_scripts', 'snmpsim-command-responder')()
  File "/Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages/snmpsim-1.0.0-py2.7.egg/snmpsim/commands/responder.py", line 510, in main
    variation_modules, mode='variating')
  File "/Users/tkekan/oracle/wrk/snmp-poller/poller-venv/lib/python2.7/site-packages/snmpsim-1.0.0-py2.7.egg/snmpsim/variation.py", line 256, in initialize_variation_modules
    for name, modules_contexts in variation_modules.items():
AttributeError: 'int' object has no attribute 'items'

**Comment by tkekan** [comment]
After pointing it to the variations modules dir, didn't see the error. 

CLI used snmpsim-command-responder --data-dir=./data --variation-modules-dir=./variation --agent-udpv4-endpoint=127.0.0.1:1024
