### ISSUE TITLE
Unable to record from MIB

### ISSUE THREAD

**Issue by thomasbromehead** [etingof/snmpsim#163]
Hi Ilya,
Thomas again... lol
Been trying to create .snmprec files from MIB files using `snmpsim-record-mibs` but I'm getting the following error:
```python
len(args.string_pool)
*** TypeError: object of type 'NoneType' has no len()
```
Tried with several MIBs including SNMPv2-MIB which is provided by default in /site-packages/snmpsim etc as well as a correctly formatted one from a DAHUA camera.
Set a breakpoint with PDB and couldn't fathom why args.string_pool was NoneType, this is what I get when I call `args.string_pool`: 
 ```bash
`(Pdb) args.string_pool
syntax = <DisplayString schema object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 0, 255>, <ValueSizeConstraint object, consts 0, 255>>, encoding iso-8859-1>
hint = '# Scalar SNMPv2-MIB::sysDescr (type DisplayString)\r\n'
automatic_values = 5000
```
`args`seems like a very weird object, I can call non-existing methods on it, even on args.string_pool: 
`args.string_pool.asdadasda` yields the same result as above...

__This is the stacktrace__:
`Traceback (most recent call last):
  File "/home/thomas/snmp-project/venv/bin/snmpsim-record-mibs", line 8, in <module>
    sys.exit(main())
  File "/home/thomas/snmp-project/venv/lib/python3.8/site-packages/snmpsim/commands/mib2rec.py", line 472, in main
    val = get_value(node.syntax, hint)
  File "/home/thomas/snmp-project/venv/lib/python3.8/site-packages/snmpsim/commands/mib2rec.py", line 240, in get_value
    val = ' '.join([args.string_pool[random.randrange(0, len(args.string_pool))]
  File "/home/thomas/snmp-project/venv/lib/python3.8/site-packages/snmpsim/commands/mib2rec.py", line 240, in <listcomp>
    val = ' '.join([args.string_pool[random.randrange(0, len(args.string_pool))]
TypeError: object of type 'NoneType' has no len()`

**Comment by wanglong001** [comment]
+1

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/14817376/174588291-85b16ff3-dbfa-49fd-8598-b2652314696c.png">

**Comment by BURNI80** [comment]
I have this error pls help
![image](https://github.com/etingof/snmpsim/assets/77487911/2623e9ea-857b-4cc6-ab84-80e9194a83ac)

**Comment by lextm** [comment]
`snmpsim-lextudio` version 1.0.3 contains the fix.

@BURNI80 You didn't compile AGENTX-MIB properly and `mibdump --destination-directory=pysnmp_mibs ./AGENTX-MIB.txt` is necessary to ensure you use the proper MIB document and compile it to .py. Then your `snmpsim-record-mibs` command might start to work.

You are welcome to read etingof/pysnmp/issues/429 to learn more.

**Comment by BURNI80** [comment]
Thank you!

Why when I execute: `snmpsim-record-mibs --mib-module=BRIDGE-MIB` it ask me for values?

![image](https://github.com/etingof/snmpsim/assets/77487911/c3a99d46-5230-4b4d-935e-e03536a6ed90)

What do I have to write?

**Comment by lextm** [comment]
@BURNI80 if you read the actual MIB documents, you will see that `dot1dBaseBridgeAddress` is of the type `MacAddress`, which in turn is `OCTET STRING (SIZE (6))`

https://github.com/lextudio/sharpsnmppro-mib/blob/master/SNMPv2-TC.txt#L92

So when prompted to input value, you might use something like `AAAAAA` to meet the constraint.

Similarly you need the following (and more),

* A value like `600` for `dot1dStpBridgeMaxAge`.
* A value like `100` for `dot1dStpBridgeHelloTime`.
* A value like `400` for `dot1dStpBridgeForwardDelay`.
* A value like `aa` for `dot1dStpPortDesignatedPort`.

**Comment by BURNI80** [comment]
@lextm 

Thanks!!! Anyway to do it full automatic?

What command I need to compile AGENTX-MIB.py to a .snmprec file?

Any idea of why some mibs return 0 OIDs?
![image](https://github.com/etingof/snmpsim/assets/77487911/a21a56a9-f57d-439c-b03d-8d6e613c829d)

And why is generated like this? I mean, with taht strange OIDs
![image](https://github.com/etingof/snmpsim/assets/77487911/28a370c9-116c-4e5c-a4ff-8dcf03042f8c)
![image](https://github.com/etingof/snmpsim/assets/77487911/0b4ed81f-58f7-4db2-98cf-734f94dfa835)
