### ISSUE TITLE
Malformed Object ID when try to convert snmpwalk in datafile.py

### ISSUE THREAD

**Issue by landy2005** [etingof/snmpsim#38]
I try converting snmpwalk to snmprec format:
```
$ datafile.py --source-record-type=snmpwalk --input-file=walk.txt
# Input file #0, processing records from the beginning till the end
Traceback (most recent call last):
  File "/usr/local/bin/datafile.py", line 202, in <module>
    oid, value = recordsSet[srcRecordType].evaluate(line, backdoor=backdoor)
  File "/usr/local/lib/python3.5/dist-packages/snmpsim/record/dump.py", line 42, in evaluate
    oid = self.evaluateOid(oid)
  File "/usr/local/lib/python3.5/dist-packages/snmpsim/record/dump.py", line 20, in evaluateOid
    return univ.ObjectIdentifier(oid)
  File "/usr/local/lib/python3.5/dist-packages/pyasn1/type/base.py", line 240, in __init__
    value = self.prettyIn(value)
  File "/usr/local/lib/python3.5/dist-packages/pyasn1/type/univ.py", line 1191, in prettyIn
    'Malformed Object ID %s at %s: %s' % (value, self.__class__.__name__, sys.exc_info()[1])
pyasn1.error.PyAsn1Error: Malformed Object ID SNMPv2-MIB::sysDescr.0 at ObjectIdentifier: None
```

File [walk.txt](https://github.com/etingof/snmpsim/files/2004841/walk.txt) attached

```
# pip list
Package               Version
--------------------- ----------------------
chardet               3.0.4
command-not-found     0.3
devscripts            2.16.2ubuntu3
language-selector     0.1
Magic-file-extensions 0.2
pip                   10.0.1
ply                   3.10
pyasn1                0.4.2
pycryptodome          3.4.5
pycryptodomex         3.4.7
pycurl                7.43.0
pygobject             3.20.0
PyMySQL               0.7.9
pysmi                 0.3.0
pysnmp                4.4.4
python-apt            1.1.0b1+ubuntu0.16.4.1
python-debian         0.1.27
python-systemd        231
requests              2.9.1
setuptools            20.7.0
six                   1.10.0
snmpsim               0.4.4
ssh-import-id         5.5
ufw                   0.35
unattended-upgrades   0.1
urllib3               1.22
virtualenv            15.0.1
```

**Comment by landy2005** [comment]
@etingof no any suggestions?

**Comment by etingof** [comment]
Oh, my goodness, I beg your pardon for overlooking this issue!

The problem is actually very simple - you should run your `snmpwalk` in a way that it produces just OIDs, not MIB names (e.g. `snmpwalk -On`). Here is [the doc](http://snmplabs.com/snmpsim/building-simulation-data.html#using-snmpwalk-reporting) on that.

**Comment by landy2005** [comment]
@etingof I know, this is simple way..
but I have contributed walks, which not possible for re-walk again.

**Comment by etingof** [comment]
Well, one thing you could potentially do right away is to cut MIB object part from each string of your .snmpwalk files and pass them through `snmptranslate -On` tool which would turn MIB names into plain OIDs *if* you have [all the MIBs](http://mibs.snmplabs.com/asn1/) your .snmpwalk files reference. One resolved, you could re-construct each .snmpwalk file with plain OIDs.

I mean all this to be done by script, not by hand obviously. ;-)

Another thing would be to make the `datafile` tool calling pysmi for the same purpose, which would be a nice feature indeed.

Either way, we are dependent on the referenced MIBs availability here.
