### ISSUE TITLE
Exception with Walkling snmpAgent by snmprec.py

### ISSUE THREAD

**Issue by chengshuangliu** [etingof/snmpsim#46]
```
Exception Log:
2018-08-30 01:57:25,038 snmprec: OIDs dumped: 0/32800
2018-08-30 01:57:25,077 snmprec: OIDs dumped: 65650, elapsed: 180.19 sec, rate: 182.00 OIDs/sec, errors: 0
2018-08-30 01:57:25,077 snmprec: Traceback (most recent call last):;
2018-08-30 01:57:25,077 snmprec:   File "/usr/local/lib/python2.7/dist-packages/snmpsim-0.4.5-py2.7.egg/EGG-INFO/scripts/snmprec.py", line 745, in <module>;    snmpEngine.transportDispatcher.runDispatcher();
2018-08-30 01:57:25,077 snmprec:   File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher;    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())));
2018-08-30 01:57:25,077 snmprec: PySnmpError: poll error: Traceback (most recent call last):;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher;    use_poll=True, map=self.__sockMap, count=1);;  File "/usr/lib/python2.7/asyncore.py", line 220, in loop;    poll_fun(timeout, map);;  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2;    readwrite(obj, flags);;  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite;    obj.handle_error();;  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite;    obj.handle_read_event();;  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event;    self.handle_read();;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read;    self._cbFun(self, transportAddress, incomingMessage);;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/base.py", line 70, in _cbFun;    self, transportDomain, transportAddress, incomingMessage;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun;    self, transportDomain, transportAddress, wholeMsg;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/proto/rfc3412.py", line 328, in receiveMessage;    snmpEngine, transportDomain, transportAddress, wholeMsg;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/proto/mpmod/rfc2576.py", line 289, in prepareDataElements;    securityModel, securityLevel, wholeMsg, msg;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/proto/secmod/rfc2576.py", line 405, in processIncomingMsg;    maxSizeResponseScopedPDU = maxMessageSize - 128;;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 136, in __sub__;    return self.clone(self._value - value);;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 349, in clone;    return self.__class__(value, **initilaizers);;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 103, in __init__;    base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs);;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 236, in __init__;    Asn1ItemBase.__init__(self, **kwargs);;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 46, in __init__;    readOnly.update(kwargs);;ValueError: dictionary update sequence element #0 has length 11; 2 is required;;
```

```
cliu@ubuntu:~$ pip list
adium-theme-ubuntu (0.3.4)
MySQL-python (1.2.4)
pip (8.1.1)
ply (3.11)
pyasn1 (0.4.4)
pycryptodomex (3.6.4)
pysmi (0.3.1)
pysnmp (4.4.4)
setuptools (20.7.0)
snmpsim (0.4.5)
unity-lens-photos (1.0)
wheel (0.29.0)
cliu@ubuntu:~$ 
```

**Comment by chengshuangliu** [comment]
Exception Log:
2018-08-30 01:57:25,038 snmprec: OIDs dumped: 0/32800
2018-08-30 01:57:25,077 snmprec: OIDs dumped: 65650, elapsed: 180.19 sec, rate: 182.00 OIDs/sec, errors: 0
2018-08-30 01:57:25,077 snmprec: Traceback (most recent call last):;
2018-08-30 01:57:25,077 snmprec:   File "/usr/local/lib/python2.7/dist-packages/snmpsim-0.4.5-py2.7.egg/EGG-INFO/scripts/snmprec.py", line 745, in <module>;    snmpEngine.transportDispatcher.runDispatcher();
2018-08-30 01:57:25,077 snmprec:   File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher;    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())));
2018-08-30 01:57:25,077 snmprec: PySnmpError: poll error: Traceback (most recent call last):;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher;    use_poll=True, map=self.__sockMap, count=1);;  File "/usr/lib/python2.7/asyncore.py", line 220, in loop;    poll_fun(timeout, map);;  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2;    readwrite(obj, flags);;  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite;    obj.handle_error();;  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite;    obj.handle_read_event();;  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event;    self.handle_read();;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read;    self._cbFun(self, transportAddress, incomingMessage);;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/base.py", line 70, in _cbFun;    self, transportDomain, transportAddress, incomingMessage;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun;    self, transportDomain, transportAddress, wholeMsg;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/proto/rfc3412.py", line 328, in receiveMessage;    snmpEngine, transportDomain, transportAddress, wholeMsg;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/proto/mpmod/rfc2576.py", line 289, in prepareDataElements;    securityModel, securityLevel, wholeMsg, msg;;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/proto/secmod/rfc2576.py", line 405, in processIncomingMsg;    maxSizeResponseScopedPDU = maxMessageSize - 128;;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 136, in __sub__;    return self.clone(self._value - value);;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 349, in clone;    return self.__class__(value, **initilaizers);;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 103, in __init__;    base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs);;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 236, in __init__;    Asn1ItemBase.__init__(self, **kwargs);;  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 46, in __init__;    readOnly.update(kwargs);;ValueError: dictionary update sequence element #0 has length 11; 2 is required;;

**Comment by etingof** [comment]
Could you please upgrade to `pysnmp 4.4.5`? I think this bug should have been fixed there.

**Comment by chengshuangliu** [comment]
Hi etingof，
Thank you for your replying，I'll upgrade pysnmp to 4.4.5.
