### ISSUE TITLE
Pip install on windows is not enough

### ISSUE THREAD

**Issue by Benik3** [etingof/snmpsim#57]
Hello.

On windows the simulator can't be simply installed with `pip install snmpsim.`
I had to download the repository and run `python setup.py install` from the folder to get the simulator to work, which I found accidentally in issue #14 . This setup file is not included in the pip installation. The download version must be same (last release is now 0.4.6, on pip is 0.4.5)

It took me a while to figure it out. Would be nice to have it in wiki or working pip installation.

After successful install I found, that SNMP-error 1 (TooBig) is not possible to simulate, but never mind :D

**Comment by etingof** [comment]
Thanks for reporting this!

If you happen to come up with a PR fixing the issues you've run into, I'd happily merge it. ;-)

**Comment by GhostofGoes** [comment]
What's the specific issue you're having? And what version of Windows, Python, and Pip were you using?

It works for me on Windows 10 with Python 3.7 and Pip 18.1, though the scripts will try to open in a new window by default.

**Comment by etingof** [comment]
> though the scripts will try to open in a new window by default.

I am thinking to finally move these scripts to [entry_points](https://packaging.python.org/specifications/entry-points/). I wonder if this would make them better citizens on Windows...?

**Comment by Benik3** [comment]
Windows 10 1803
Pip 18.01 and 19.0.1 tested
Python 3.7.2

When I install it through Pip and try to run it, I got this error:
```
Traceback (most recent call last):
  File "C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts\snmpsimd.py", line 763, in <module>
    with daemon.PrivilegesOf(procUser, procGroup):
AttributeError: module 'snmpsim.daemon' has no attribute 'PrivilegesOf'
```

**Comment by etingof** [comment]
Oh, no! That's a bug hopefully fixed in master (by commit e1878acaa41bd79761ebc73ab21431e365d98d57). I wonder if you could try it out before I release the fixed version?

**Comment by Benik3** [comment]
Now I got this (without the setup install). If I run setup.py it works ok as before.
`Traceback (most recent call last):
  File "C:\Users\d-benes\Desktop\snmpsim-master\scripts\snmpsimd.py", line 41, in <module>
    from snmpsim.error import SnmpsimError, NoDataNotification
ModuleNotFoundError: No module named 'snmpsim.error'`

**Comment by etingof** [comment]
Thank you for testing that! I assume that properly installed master version works alright for you.

The bug you've encountered has been introduced in 0.4.6.

**Comment by Benik3** [comment]
No problem, thanks for your work :)

**Comment by etingof** [comment]
> After successful install I found, that SNMP-error 1 (TooBig) is not possible to simulate, but never mind :D

Yup, that bit seems to be missing in pysnmp and (subsequently) in snmpsim. We should probably approach this from pysnmp side...

**Comment by etingof** [comment]
> This setup file is not included in the pip installation. The download version must be same (last release is now 0.4.6, on pip is 0.4.5)

One more thing: is this ^ resolved or something still needs to be done about it?

**Comment by Benik3** [comment]
Should the **snmpsim-0.4.6-py3.7.eg**g folder in **C:\Users\\%username%\AppData\Local\Programs\Python\Python37\Lib\site-packages** create automatically?
If yes, that the pip installation in 0.4.6 is same as in 0.4.5.

But for some reason, I'm not able now to run 0.4.6 even with the manual run of the setup.py.
After install I get:  
```
Traceback (most recent call last):
  File "C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts\snmpsimd.py", line 4, in <module>
    __import__('pkg_resources').run_script('snmpsim==0.4.6', 'snmpsimd.py')
  File "C:\Users\d-benes\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\d-benes\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 1435, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/snmpsimd.py' not found in metadata at 'c:\\users\\d-benes\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\snmpsim-0.4.6.dist-info'
```

This is how the whole installation looks like:  
```
Microsoft Windows [Version 10.0.17134.471]
(c) 2018 Microsoft Corporation. Všechna práva vyhrazena.

C:\Users\d-benes>pip install snmpsim
Collecting snmpsim
  Using cached https://files.pythonhosted.org/packages/44/68/1e64cdfebd954029dfd74b1855a29fcdf3eb1ee32eeaed566ed36e8d2719/snmpsim-0.4.6-py2.py3-none-any.whl
Collecting pysnmp<5.0.0,>=4.4.3 (from snmpsim)
  Using cached https://files.pythonhosted.org/packages/ee/4f/c5641a878b91dc7575c7193efdbc1aaf3fa409285ca7a9a27c04ddd1406f/pysnmp-4.4.8-py2.py3-none-any.whl
Collecting pyasn1>=0.2.3 (from pysnmp<5.0.0,>=4.4.3->snmpsim)
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Collecting pycryptodomex (from pysnmp<5.0.0,>=4.4.3->snmpsim)
  Using cached https://files.pythonhosted.org/packages/74/85/f8e54ad879a881c5f4d6befffaae8263a28b56256b8c5dd47f4486de220e/pycryptodomex-3.7.3-cp37-cp37m-win_amd64.whl
Collecting pysmi (from pysnmp<5.0.0,>=4.4.3->snmpsim)
  Using cached https://files.pythonhosted.org/packages/e0/e0/328b765ff44150f2ac08f7e36f35623764ab55db22602b613f4eb437558f/pysmi-0.3.3-py2.py3-none-any.whl
Collecting ply (from pysmi->pysnmp<5.0.0,>=4.4.3->snmpsim)
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Installing collected packages: pyasn1, pycryptodomex, ply, pysmi, pysnmp, snmpsim
Successfully installed ply-3.11 pyasn1-0.4.5 pycryptodomex-3.7.3 pysmi-0.3.3 pysnmp-4.4.8 snmpsim-0.4.6
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\d-benes>snmpsimd.py --data-dir=./data --agent-udpv4-endpoint=127.0.0.1:1024
Traceback (most recent call last):
  File "C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts\snmpsimd.py", line 763, in <module>
    with daemon.PrivilegesOf(procUser, procGroup):
AttributeError: module 'snmpsim.daemon' has no attribute 'PrivilegesOf'

C:\Users\d-benes>cd "C:\Users\d-benes\Desktop\snmpsim-0.4.6"

C:\Users\d-benes\Desktop\snmpsim-0.4.6>python setup.py install
running install
running bdist_egg
running egg_info
writing snmpsim.egg-info\PKG-INFO
writing dependency_links to snmpsim.egg-info\dependency_links.txt
writing requirements to snmpsim.egg-info\requires.txt
writing top-level names to snmpsim.egg-info\top_level.txt
reading manifest file 'snmpsim.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'snmpsim.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\snmpsim
copying build\lib\snmpsim\confdir.py -> build\bdist.win-amd64\egg\snmpsim
copying build\lib\snmpsim\daemon.py -> build\bdist.win-amd64\egg\snmpsim
copying build\lib\snmpsim\error.py -> build\bdist.win-amd64\egg\snmpsim
creating build\bdist.win-amd64\egg\snmpsim\grammar
copying build\lib\snmpsim\grammar\abstract.py -> build\bdist.win-amd64\egg\snmpsim\grammar
copying build\lib\snmpsim\grammar\dump.py -> build\bdist.win-amd64\egg\snmpsim\grammar
copying build\lib\snmpsim\grammar\mvc.py -> build\bdist.win-amd64\egg\snmpsim\grammar
copying build\lib\snmpsim\grammar\sap.py -> build\bdist.win-amd64\egg\snmpsim\grammar
copying build\lib\snmpsim\grammar\snmprec.py -> build\bdist.win-amd64\egg\snmpsim\grammar
copying build\lib\snmpsim\grammar\walk.py -> build\bdist.win-amd64\egg\snmpsim\grammar
copying build\lib\snmpsim\grammar\__init__.py -> build\bdist.win-amd64\egg\snmpsim\grammar
copying build\lib\snmpsim\log.py -> build\bdist.win-amd64\egg\snmpsim
copying build\lib\snmpsim\mltsplit.py -> build\bdist.win-amd64\egg\snmpsim
creating build\bdist.win-amd64\egg\snmpsim\record
copying build\lib\snmpsim\record\abstract.py -> build\bdist.win-amd64\egg\snmpsim\record
copying build\lib\snmpsim\record\dump.py -> build\bdist.win-amd64\egg\snmpsim\record
copying build\lib\snmpsim\record\mvc.py -> build\bdist.win-amd64\egg\snmpsim\record
copying build\lib\snmpsim\record\sap.py -> build\bdist.win-amd64\egg\snmpsim\record
creating build\bdist.win-amd64\egg\snmpsim\record\search
copying build\lib\snmpsim\record\search\database.py -> build\bdist.win-amd64\egg\snmpsim\record\search
copying build\lib\snmpsim\record\search\file.py -> build\bdist.win-amd64\egg\snmpsim\record\search
copying build\lib\snmpsim\record\search\__init__.py -> build\bdist.win-amd64\egg\snmpsim\record\search
copying build\lib\snmpsim\record\snmprec.py -> build\bdist.win-amd64\egg\snmpsim\record
copying build\lib\snmpsim\record\walk.py -> build\bdist.win-amd64\egg\snmpsim\record
copying build\lib\snmpsim\record\__init__.py -> build\bdist.win-amd64\egg\snmpsim\record
copying build\lib\snmpsim\__init__.py -> build\bdist.win-amd64\egg\snmpsim
byte-compiling build\bdist.win-amd64\egg\snmpsim\confdir.py to confdir.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\daemon.py to daemon.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\error.py to error.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\grammar\abstract.py to abstract.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\grammar\dump.py to dump.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\grammar\mvc.py to mvc.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\grammar\sap.py to sap.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\grammar\snmprec.py to snmprec.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\grammar\walk.py to walk.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\grammar\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\log.py to log.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\mltsplit.py to mltsplit.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\abstract.py to abstract.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\dump.py to dump.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\mvc.py to mvc.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\sap.py to sap.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\search\database.py to database.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\search\file.py to file.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\search\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\snmprec.py to snmprec.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\walk.py to walk.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\record\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\snmpsim\__init__.py to __init__.cpython-37.pyc
installing package data to build\bdist.win-amd64\egg
running install_data
creating build\bdist.win-amd64\egg\snmpsim\variation
copying variation\delay.py -> build\bdist.win-amd64\egg\snmpsim\variation
copying variation\error.py -> build\bdist.win-amd64\egg\snmpsim\variation
copying variation\multiplex.py -> build\bdist.win-amd64\egg\snmpsim\variation
copying variation\notification.py -> build\bdist.win-amd64\egg\snmpsim\variation
copying variation\numeric.py -> build\bdist.win-amd64\egg\snmpsim\variation
copying variation\redis.py -> build\bdist.win-amd64\egg\snmpsim\variation
copying variation\sql.py -> build\bdist.win-amd64\egg\snmpsim\variation
copying variation\subprocess.py -> build\bdist.win-amd64\egg\snmpsim\variation
copying variation\writecache.py -> build\bdist.win-amd64\egg\snmpsim\variation
creating build\bdist.win-amd64\egg\snmpsim\data
copying data\public.snmprec -> build\bdist.win-amd64\egg\snmpsim\data
creating build\bdist.win-amd64\egg\snmpsim\data\1.3.6.1.6.1.1.0
copying data\1.3.6.1.6.1.1.0\127.0.0.1.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\1.3.6.1.6.1.1.0
creating build\bdist.win-amd64\egg\snmpsim\data\foreignformats
copying data\foreignformats\linux.snmpwalk -> build\bdist.win-amd64\egg\snmpsim\data\foreignformats
copying data\foreignformats\winxp1.snmpwalk -> build\bdist.win-amd64\egg\snmpsim\data\foreignformats
copying data\foreignformats\winxp2.sapwalk -> build\bdist.win-amd64\egg\snmpsim\data\foreignformats
creating build\bdist.win-amd64\egg\snmpsim\data\mib2dev
copying data\mib2dev\host-resources-mib.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\mib2dev
copying data\mib2dev\ip-mib.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\mib2dev
copying data\mib2dev\tcp-mib.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\mib2dev
copying data\mib2dev\udp-mib.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\mib2dev
creating build\bdist.win-amd64\egg\snmpsim\data\public
copying data\public\1.3.6.1.2.1.100.1.13.0.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\public
creating build\bdist.win-amd64\egg\snmpsim\data\public\1.3.6.1.2.1.100.1.2.0
copying data\public\1.3.6.1.2.1.100.1.2.0\__1.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\public\1.3.6.1.2.1.100.1.2.0
creating build\bdist.win-amd64\egg\snmpsim\data\public\1.3.6.1.6.1.1.0
copying data\public\1.3.6.1.6.1.1.0\127.0.0.1.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\public\1.3.6.1.6.1.1.0
creating build\bdist.win-amd64\egg\snmpsim\data\recorded
copying data\recorded\linksys-system.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\recorded
copying data\recorded\linux-full-walk.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\recorded
copying data\recorded\solaris-system.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\recorded
copying data\recorded\udp-endpoint-table-walk.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\recorded
copying data\recorded\winxp-full-walk.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\recorded
creating build\bdist.win-amd64\egg\snmpsim\data\variation
copying data\variation\delay.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation
copying data\variation\error.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation
copying data\variation\multiplex.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation
copying data\variation\notification.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation
copying data\variation\sql.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation
copying data\variation\subprocess.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation
copying data\variation\virtualtable.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation
copying data\variation\writecache.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation
creating build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00000.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00001.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00002.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00003.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00004.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00005.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00006.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00007.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00008.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00009.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
copying data\variation\multiplex\00010.snmprec -> build\bdist.win-amd64\egg\snmpsim\data\variation\multiplex
creating build\bdist.win-amd64\egg\EGG-INFO
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
creating build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.7\datafile.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.7\mib2dev.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.7\pcap2dev.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.7\snmprec.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.7\snmpsimd.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying snmpsim.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying snmpsim.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying snmpsim.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying snmpsim.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying snmpsim.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying snmpsim.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating 'dist\snmpsim-0.4.6-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing snmpsim-0.4.6-py3.7.egg
creating c:\users\d-benes\appdata\local\programs\python\python37\lib\site-packages\snmpsim-0.4.6-py3.7.egg
Extracting snmpsim-0.4.6-py3.7.egg to c:\users\d-benes\appdata\local\programs\python\python37\lib\site-packages
Adding snmpsim 0.4.6 to easy-install.pth file
Installing datafile.py script to C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts
Installing mib2dev.py script to C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts
Installing pcap2dev.py script to C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts
Installing snmprec.py script to C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts
Installing snmpsimd.py script to C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts

Installed c:\users\d-benes\appdata\local\programs\python\python37\lib\site-packages\snmpsim-0.4.6-py3.7.egg
Processing dependencies for snmpsim==0.4.6
Searching for pysnmp==4.4.8
Best match: pysnmp 4.4.8
Adding pysnmp 4.4.8 to easy-install.pth file

Using c:\users\d-benes\appdata\local\programs\python\python37\lib\site-packages
Searching for pysmi==0.3.3
Best match: pysmi 0.3.3
Adding pysmi 0.3.3 to easy-install.pth file

Using c:\users\d-benes\appdata\local\programs\python\python37\lib\site-packages
Searching for pycryptodomex==3.7.3
Best match: pycryptodomex 3.7.3
Adding pycryptodomex 3.7.3 to easy-install.pth file

Using c:\users\d-benes\appdata\local\programs\python\python37\lib\site-packages
Searching for pyasn1==0.4.5
Best match: pyasn1 0.4.5
Adding pyasn1 0.4.5 to easy-install.pth file

Using c:\users\d-benes\appdata\local\programs\python\python37\lib\site-packages
Searching for ply==3.11
Best match: ply 3.11
Adding ply 3.11 to easy-install.pth file

Using c:\users\d-benes\appdata\local\programs\python\python37\lib\site-packages
Finished processing dependencies for snmpsim==0.4.6

C:\Users\d-benes\Desktop>snmpsimd.py --data-dir=./data --agent-udpv4-endpoint=127.0.0.1:1024
Traceback (most recent call last):
  File "C:\Users\d-benes\AppData\Local\Programs\Python\Python37\Scripts\snmpsimd.py", line 4, in <module>
    __import__('pkg_resources').run_script('snmpsim==0.4.6', 'snmpsimd.py')
  File "C:\Users\d-benes\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\d-benes\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 1435, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/snmpsimd.py' not found in metadata at 'c:\\users\\d-benes\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\snmpsim-0.4.6.dist-info'

C:\Users\d-benes\Desktop\snmpsim-0.4.6>
```

**Comment by GhostofGoes** [comment]
@etingof Yes, setuptools entrypoints are much better behaved on Windows. It would likely fix most of these issues, in addition to being slightly cleaner (`snmpsimd` versus `snmpsimd.py`).

**Comment by etingof** [comment]
> @etingof Yes, setuptools entrypoints are much better behaved on Windows. It would likely fix most of these issues, in addition to being slightly cleaner (`snmpsimd` versus `snmpsimd.py`).

This is coming! Thanks!

**Comment by etingof** [comment]
> AttributeError: module 'snmpsim.daemon' has no attribute 'PrivilegesOf'

This should be fixed in the latest released snmpsim.
